In [1]:
import numpy as np

##  Lesson 05 - Using the Built-in functions you learned about in the previous lesson, create a 4 x 4 ndarray that onlycontains consecutive even numbers from 2 to 32 (inclusive)

In [4]:
x = np.arange(2,33,2).reshape(4,4)
print(x)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [6]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]] )

## Lesson 10 - Manipulation arrays

In [16]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26)


# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[(X % 2) == 1]
Y


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

## Lesson 12 - Creating ndarrays with Broadcasting

In [19]:
x = np.ones((4,4)) * np.arange(1,5)
x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])