In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = np.int64)

In [ ]:
print('X has dimensions:', x.shape)
print('X has a total of', x.size, 'elements')
print('X is an object of type:', type(x))
print('The elements in Y are of type:', x.dtype)

In [ ]:
np.save('my_array', x)

In [ ]:
y = np.load('my_array.npy')
print('Y has dimensions:', y.shape)

## Lesson 6 - Using built-in function to create ndarrays


In [ ]:
#Creating a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

#Creating a 3 x 2 ndarray full of ones. 
Y = np.ones((3,2))

#Creating a 2 x 3 ndarray full of fives. 
Z = np.full((2,3), 5) 

#Creating a 5 x 5 Identity matrix. 
A = np.eye(5)

# Creating a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50 on its main diagonal
B = np.diag([10,20,30,50])

In [ ]:
#Creating a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

#Creating a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

#Creating a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

#Creating a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)

#Creating a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,with 25 excluded.
x = np.linspace(0,25,10, endpoint = False)



In [ ]:
#Reshaping x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We create a a rank 1 ndarray with sequential integers from 0 to 19 and reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50, with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

## Lesson 7 - Accessing, Deleting, and Inserting Elements Into ndarrays

In [ ]:
X = np.arange(2,9,2)
Y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(X)
print(Y)

### Deleting elements

In [ ]:
#np.delete(ndarray, elements, axis), axis = 0 is rows, axis = 1 is columns

In [ ]:
X = np.delete(X, [1,3])
Y = np.delete(Y, 0, axis = 0)
print("X = ", X)
print("Y = ", Y)

In [ ]:
Y = np.delete(Y, [0,2], axis = 1)
print("Y = ", Y)

### Apending elements into arrays

In [ ]:
#np.append(ndarray, elements, axis), axis = 0 is rows, axis = 1 is columns

In [ ]:
X = np.append(X, [10, 12])
Y = np.append(Y, [[10, 11, 12]], axis = 0)
print()
print('X = ', X)
print()
print('Y = ', Y)

In [ ]:
Y = np.append(Y, [[100], [200], [300], [400]], axis = 1)
print('Y = ', Y)

### Inserting elements into arrays

In [ ]:
# np.insert(ndarray, index, elements, axis)
print()
print('X = ', X)
print('Y = ', Y)

In [ ]:
X = np.insert(X, 1, [100,200])
Y = np.insert(Y, 1, [99, 99, 99], axis = 0)
Y = np.insert(Y, 1, [99, 99, 99, 99], axis = 1)
print('X = ', X)
print('Y = ', Y)

### Stacking arrays each other

In [ ]:
print('X = ', X)
print('Y = ', Y)

In [ ]:
Z = np.vstack((X, Y))


In [ ]:
Z

In [ ]:
Y = np.hstack((Y, X.reshape(3,1)))
Y

## Lesson 8 - Slicing Arrays

In [ ]:
X = np.arange(20).reshape(4, 5)
print()
print('X = \n', X)
print()

Z = X[2:4, 1:3]   
print('Z = \n', Z)

W = X[2:,1:3]
print()
print('W = \n', W)

# We select all the elements in the 4rd row
v = X[3, :]
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
e = X[:, 2:3]
print()
print('e = ', e)

### Extracting elements from the diagonal

In [ ]:
# np.diag(ndarray, k=N), K >1 is above the diagonal,  K < 1 is below the diagonal

In [ ]:
Y = X.copy()
print('Y =', Y)
print()

# We print the elements in the main diagonal of Y
print('z =', np.diag(Y))
print()

# We print the elements above the main diagonal of Y
print('y =', np.diag(Y, k = 2))
print()

# We print the elements below the main diagonal of Y
print('w = ', np.diag(Y, k = -2))


# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of Y 
print('The unique elements in X are:',np.unique(X))

## Lesson 9 - Boolean Indexing, Set Operations, Sorting

In [ ]:
x = np.arange(25).reshape(5,5)
x

### Boolean Indexing

In [ ]:
print('The elements in X that are greater than 10:', x[x > 10])
print('The elements in X that less than or equal to 7:', x[x <= 7])
print('The elements in X that are between 10 and 17:', x[(x > 10) & (x < 17)])

In [ ]:
x[(x > 10) & (x < 15)] = - 1
x

### Set Operations

In [ ]:
y = np.random.randint(1,10, size = (10))
y

In [ ]:
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

### Sorting

In [ ]:
# np.sort(ndarray) as a function -> does not sort the original array
# ndarray.sort() as a method -> does sort the original array

In [ ]:
# Sorting rank 1 array

x = np.random.randint(1,11,size=(10,))
print('Sorted x (out of place):', np.sort(x))
print('x after sorting:', x)
y = np.random.randint(1,11,size=(10,))
y.sort()
print('y after sorting:', y)

# We sort x but only keep the unique elements in x
print('Sorted x with unique elements in x', np.sort(np.unique(x)))

In [ ]:
# Sorting rank 2 array
X = np.random.randint(1,11,size=(5,5))

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0)) #axis = 0 -> column

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1)) #axis = 1 -> row

## Lesson 11 - Arithmetic Operations

In [141]:
X = np.array([[1,2], [3,4]])

print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [167]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a)
print(b)

[ 0. 10. 20. 30.]
[1. 2. 3.]


In [173]:
c = a[:, np.newaxis] + b
c

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])